### PR TITLE
French (fr-FR) translation for 3.0.0 RC1

### PR DESCRIPTION
**Pull request by ebeauchamps**

### CODE REVIEW

**Comment by takobell** [comment]
I'm showing 26 conflicts with the PR and it looks like maybe a commit from Nov 6 was accidentally included?  Would you mind resolving those or it might be easier to starting with a fresh PR?

**Comment by ebeauchamps** [comment]
Hello Brad.

I am going to try to revert those commits in order to start over with a fresh new one. I am not very Github savvy so It could take some time.

Thanks for your understanding.

Emmanuel


________________________________
De : Brad Bell <notifications@github.com>
Envoyé : mardi 12 décembre 2017 00:05
À : craftcms/cms
Cc : Emmanuel Beauchamps; Author
Objet : Re: [craftcms/cms] French (fr-FR) translation for 3.0.0 RC1 (#2172)


I'm showing 26 conflicts with the PR and it looks like maybe a commit from Nov 6 was accidentally included? Would you mind resolving those or it might be easier to starting with a fresh PR?

**Comment by takobell** [comment]
No worries at all, @ebeauchamps! Going to go ahead and close this one out, then.

**Comment by brandonkelly** [comment]
@ebeauchamps No need to re-commit. I just manually merged all of your changes into Craft. Thanks for your help!!

**Comment by ebeauchamps** [comment]
Thank you Sir for your time!

**Pull request closed without merging**
