### PR TITLE
Allow override of default address formatter

### PR DESCRIPTION
**Pull request by lukeholder**
### Description

Allows replacement of the default formatter that is used by the Addresses service.

Custom Formatter class:

```php
<?php

namespace modules;

use CommerceGuys\Addressing\AddressInterface;

class MyFormatter extends \CommerceGuys\Addressing\Formatter\DefaultFormatter
{
    public function format(AddressInterface $address, array $options = []): string
    {
        return parent::format($address, $options) . $address->phone;
    }
}
```

Inject into app config:

`app.php`

```php
'components' => [
    'addresses' => [
        'class' => \craft\services\Addresses::class,
        'formatter' => new \modules\MyFormatter(
            new \CommerceGuys\Addressing\AddressFormat\AddressFormatRepository(),
            new \CommerceGuys\Addressing\Country\CountryRepository(),
            new \CommerceGuys\Addressing\Subdivision\SubdivisionRepository()
        )
    ],
],
```

### Related issues and discussions

Craft:

https://github.com/craftcms/cms/discussions/12615

Commerce issues:

https://github.com/craftcms/commerce/issues/3152
https://github.com/craftcms/commerce/issues/3082

### CODE REVIEW

**Comment by bossanova808** [comment]
What are the odds of this one going in fairly soon?

**Comment by peteeveleigh** [comment]
Is there an estimated release date for 4.5? Are we talking days/weeks/months? 
We could really use that address card formatter asap.

**Comment by brandonkelly** [comment]
@peteeveleigh Maybe a month or so. It’s pretty stable though, and there’s no new migrations (yet, at least), so if you really need a feature, it should be safe to switch over to the `4.5` branch. To do so change your `craftcms/cms` requirement in composer.json to `4.5.x-dev as 4.5.0-alpha` and run `composer update`.

**Comment by peteeveleigh** [comment]
@brandonkelly Thanks for the update

**Comment by jonleverrier** [comment]
Something to take note of in the example code above. This will add the `phone` field to all addresses, even though that appear in PDF's (Invoices etc)

**Pull request merged**
