### PR TITLE
Twigfield integration

### PR DESCRIPTION
**Pull request by brandonkelly**
See #12119

### CODE REVIEW

**Comment by brandonkelly** [comment]
There are a couple blocking issues with Twigfield that need to get sorted out first:

- Needs to be translated into each of the languages Craft supports
- Shouldn’t break tabbing for single-line editors
- Ideally it could support <kbd>Alt</kbd> + <kbd>Tab</kbd> and <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Tab</kbd> in multi-line mode as well

**Comment by khalwat** [comment]
Twigfield has been deprecated, and replaced by [Code Editor](https://github.com/nystudio107/craft-code-editor), which is a general-purpose code editor that _also_ does Twig & autocomplete.

I pushed the changes necessary to convert this PR over to use it here (it's mostly just renaming the namespaces, along with some minor API changes):

https://github.com/khalwat/cms/tree/feature/v4-twigfield-integration

Code Editor:

* The JavaScript portion has been rewritten in TypeScript
* The tab handler mentioned above has been addressed
* Supports any language that the Monaco editor supports; examples: [JavaScript](https://github.com/doublesecretagency/craft-cpjs/pull/6), [CSS](https://github.com/doublesecretagency/craft-cpcss/pull/20)

I've already PR'd it into SEOmatic, Sprig, Preparse, CP CSS, and CP JS.

The only remaining issue is translation, which I leave to you to handle.

**Comment by khalwat** [comment]
The issues you cite have all been sorted out in `craft-code-field`: https://github.com/nystudio107/craft-code-editor

Do you plan to circle back and look at this again?

**Comment by brandonkelly** [comment]
Yeah I will, but can’t get it into 4.4 at this point. Still on my radar though…

**Pull request closed without merging**
