### PR TITLE
Add getCurrentUser convenience method

### PR DESCRIPTION
**Pull request by timkelty**
Seems like this gets written enough it warrants a helper, similar to how `request`, `response` are props.

I made it `currentUser` to match the twig global.

### CODE REVIEW

**Comment by brandonkelly** [comment]
Should be safe to have the method return `?User` rather than `?IdentityInterface`.

**Comment by timkelty** [comment]
I think so, yeah – that might have been to appease PHPstorm/stan…but yeah, the idea is you'd always get back the user element.

**Comment by timkelty** [comment]
@brandonkelly now returning `?User`

**Comment by brandonkelly** [comment]
Not really a fan of the `...$args` thing. No way of knowing what to actually pass in when calling it, without source diving into `getIdentity()`.

**Comment by timkelty** [comment]
> 

Fair enough. Just matched the signature of `\yii\web\User::getIdentity` and added an `@see`

**Pull request merged**
