### PR TITLE
Feature/clear cache compiled classes

### PR DESCRIPTION
**Pull request by khalwat**
### Description

I'd long assumed that `clear-caches/all` CLI/Utility would clear all of the runtime caches, but apparently it does not clear `storage/runtime/compiled_classes`

Adding this fixes that from a CI POV, and also fixes a nasty issue that can crop up because of it (see below):

### Related issues

https://github.com/craftcms/cms/issues/6013

^ clearing out the `storage/runtime/compiled_classes` dir addresses the issue above, something a client of mine ran into yesterday

### CODE REVIEW

**Comment by brandonkelly** [comment]
This introduces new translations so I’ve changed the base to `develop-t9n` (which is where we are putting changes that are going to require a new translation order). Can you please add the new source translations to `src/translations/en/app.php` (correctly alphabetized)? I’d do it myself but looks like I’m not allowed to modify the PR.

**Comment by khalwat** [comment]
Done ^

**Comment by brandonkelly** [comment]
Thanks!

**Comment by brandonkelly** [comment]
Finally got this released, in 3.7.39 (and 4.0.0-RC1).

**Pull request merged**
