### PR TITLE
Fixtures: generate element query with field:handle

### PR DESCRIPTION
**Pull request by boboldehampsink**

### CODE REVIEW

**Comment by boboldehampsink** [comment]
Simplified this, as the `relatedTo` syntax is not needed anymore in Craft 3.4

**Comment by boboldehampsink** [comment]
bump

**Comment by angrybrad** [comment]
Hope to get to this this week, @boboldehampsink

**Comment by angrybrad** [comment]
Thanks for your patience, @boboldehampsink... merged!

**Comment by brandonkelly** [comment]
Craft 3.4.20 is out now with this change.

**Pull request merged**
