### PR TITLE
Added new RenderElementsEvent

### PR DESCRIPTION
**Pull request by leevigraham**
The new event allows plugin / module authors to override the template rendering for the elements index container.

### CODE REVIEW

**Comment by brandonkelly** [comment]
This would be a breaking change due to the changed interface method.

**Comment by leevigraham** [comment]
> This would be a breaking change due to the changed interface method.

Is there anyway to load the source from the sourceId in the event? I think there is… let me play for an hour.

**Comment by leevigraham** [comment]
@brandonkelly fixed the PR so there's no breaking changes. The source was already being determined a few lines below so I just moved that up and included it in the event.

https://github.com/craftcms/cms/pull/6024/files#diff-73a4b977fac97aabd14c25bdc70a3d5fR583-L587

Turns out this is a very minor code change in the end.

**Comment by leevigraham** [comment]
@brandonkelly Do you need me to reissue this to fix the conflicts? I would love to see it in 3.5.

**Comment by brandonkelly** [comment]
It’s on my list to look into. Merge conflicts should be easily resolved, don’t worry about it :)

**Comment by narration-sd** [comment]
broad shoulders, as dependable, @brandonkelly - take care  :)

**Comment by leevigraham** [comment]
@brandonkelly resolved the conflicts :) as I'm working locally from my fork.

**Comment by leevigraham** [comment]
@brandonkelly  Just listened to the devode.fm podcast… 😂

**Comment by brandonkelly** [comment]
Hahaha, sorry LG :)

**Comment by leevigraham** [comment]
@brandonkelly All good, glad you like the concept. Closing this just saves me a force push and managing two forks :)

**Pull request closed without merging**
