### PR TITLE
GQL: Add asset uploader

### PR DESCRIPTION
**Pull request by timkelty**
Adds uploader to GQL asset arguments, interfaces, and mutations.

Note: based on how other things are structured, the `uploader` argument should probably be `uploaderId`? I'll leave that to you, since I didn't want to add the method to `AssetQuery` in this PR.

### CODE REVIEW

**Comment by andris-sevcenko** [comment]
Looking good, will add changelog and merge shortly!

**Comment by timkelty** [comment]
👍

@andris-sevcenko You think an `AssetQuery::uploaderId` getter should be added so the argument could be `uploaderId`? Only reason being it would match the other args like `folderId`, `volumeId`, etc.

**Comment by andris-sevcenko** [comment]
>  You think an AssetQuery::uploaderId getter should be added so the argument could be uploaderId

Yeah, maybe. I would ditch the `uploader` argument in that case, though. What do you think?

**Comment by timkelty** [comment]
Right – nix uploader arg and just have uploaderId was might thought

**Comment by brandonkelly** [comment]
Craft 3.5 RC6 is out now with this PR.

**Comment by andris-sevcenko** [comment]
@timkelty getting too close to release to change this property. Also, there's no `uploaderId` method on the `AssetQuery`, so it would require some mapping between arguments -> methods. Not hard to do, but unneeded complexity. Let's go with `uploader` for now.

**Comment by timkelty** [comment]
> Also, there's no uploaderId method on the AssetQuery

Yup, that's why I held off initially.

**Pull request merged**
