### PR TITLE
Logging tweaks

### LINKED ISSUE #10903: [4.x]: Default dev mode logging configuration should at least have a max file size
### Description

In my opinion the default logging configuration is not reasonable. I've only been working on this new site, in local dev mode only, for a few days and my logs directory was over 11 gigabytes.

```
$ ls -lh storage/logs
total 11G
-rw-r--r-- 1 bjn bjn 490K Apr  5 18:02 console-2022-04-06.log
-rw-r--r-- 1 bjn bjn 142K Apr 11 15:36 phperrors.log
-rw-r--r-- 1 bjn bjn  26M Apr  5 19:49 queue-2022-04-06.log
-rw-r--r-- 1 bjn bjn 5.8M Apr  7 16:42 queue-2022-04-07.log
-rw-r--r-- 1 bjn bjn  78M Apr  8 13:54 queue-2022-04-08.log
-rw-r--r-- 1 bjn bjn  62M Apr 11 15:36 queue-2022-04-11.log
-rw-r--r-- 1 bjn bjn 1.8G Apr  7 16:58 web-2022-04-07.log
-rw-r--r-- 1 bjn bjn 3.5G Apr  8 16:59 web-2022-04-08.log
-rw-r--r-- 1 bjn bjn 1.5G Apr  9 16:59 web-2022-04-09.log
-rw-r--r-- 1 bjn bjn 1.5G Apr 10 16:59 web-2022-04-10.log
-rw-r--r-- 1 bjn bjn 2.7G Apr 11 15:38 web-2022-04-11.log
```

Multi-gigabyte log files with only one user within a few days? I ran `tail -f storage/logs/* >just-one-thing.log` and ran a single interaction, and the resulting file was 15M!

### Steps to reproduce

1. Develop with Craft, in development mode.
2. Check logs directory

### Expected behavior

Logs have a sane maximum size. I would have suggested 10 megabytes or so but after seeing a single interaction blow that out of the water, I guess more might be necessary if the default verbosity stays so high.

### Actual behavior

Multi-gigabyte log files. Paging through them, it looks like the vast majority is SQL queries. The average developer does not need to see the exact SQL queries Craft is running under the hood.

### Opinions

I understand that detailed logs are good for super-low-level optimization or debugging. I also understand that the default verbosity in production mode is rather lower. But when developing, generally you want warnings and errors to be obvious -- a high signal-to-noise ratio -- and the finer details only matter when a problem actually occurs. In that situation you were generally the user making the interactions with your app, so you can recreate the problem, and if the logs aren't giving enough clues you can gradually turn up the verbosity when you need it. You only need to leave the app running with high verbosity logging if you're waiting for some hard-to-replicate error to show up, or if you're doing super low level optimization or debugging.

For general development, the default logs are *far* too verbose. I am not going to dig through 15 megabytes of text just after a single interaction to see what happened, especially if I don't know what the message I'm looking for might look like.

For both development and production, I think a maximum file size, at the very least, would be a huge improvement. Have you ever had a linux server unexpectedly run out of disk space? Weird, horrible things happen. That is a very real possibility if there's no file size limit like this.

I suggest the defaults are changed to have much lower default verbosity (at least in dev mode), a reasonable maximum size for log files, and ideally some better documentation with examples on how to adjust it.

### Craft CMS version

4.0.x-dev at 6e466a0

### PHP version

8.1.2

### Operating system and version

Linux 5.13.0

### Database type and version

Mysql 8.0.27

### Image driver and version

_No response_

### Installed plugins and versions

- Control Panel CSS v2.x-dev
- Formie dev-craft-4
- Navigation dev-craft-4
- Redactor 3.0.0-beta.2
- Retour 4.0.0-beta.4
- SEOmatic 4.0.0-beta.7
- Typed link field 2.1.0-rc
- Vizy dev-craft-4
- Workflow dev-craft-4

### PR DESCRIPTION
**Pull request by timkelty**
### Description
- Allow `devMode` to be set via `CRAFT_DEV_MODE` in bootstrap
- Remove `DbConfig::enableProfiling`, `DbConfig::enableLogging`
  - Configure matching `Connection` props using `devMode`
- Default log level when in `devMode` is now `LogLevel::INFO`
- SQL queries are now logged as `Craft::debug`, meaning they won't be logged by default in devMode.
- microsecond precision is disabled by default for the timestamp (enabled via `components.log.monologTargetConfig.useMicrosecondTimestamps`)
- Request context is now only logged _once per request_, not in each log.
  - It is logged with a message of `Request context`, followed by the multiline var output (if `allowLineBreaks`), otherwise as single-line json.

When hitting `actions/app/health-check` in `devMode`, this reduces the logs from `52k` to `3k` (2 lines).

### Related issues
- FIxes #10903
- https://github.com/craftcms/cms/pull/10659

## Examples:

Request with `devMode`:

With `components.log.monologTargetConfig.allowLineBreaks` set to `true`  (the default, when in `devMode`)
```
[2022-04-14T17:25:53+00:00] web.INFO: Opening DB connection: pgsql:host=postgres-13-5432.database.nitro;dbname=craft4_dev;port=5432 {"trace":[],"memory":9625984,"category":"yii\\db\\Connection::open"} 
[2022-04-14T17:25:53+00:00] web.INFO: Request context
$_GET = []

$_POST = []

$_FILES = []

$_COOKIE = []

$_SERVER = [
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    'HOSTNAME' => '4.craft.test'
    'PHP_DISPLAY_ERRORS' => 'on'
    'PHP_MEMORY_LIMIT' => '512M'
    'PHP_MAX_EXECUTION_TIME' => '5000'
    'PHP_UPLOAD_MAX_FILESIZE' => '512M'
    'PHP_MAX_INPUT_VARS' => '5000'
    'PHP_POST_MAX_SIZE' => '512M'
    'PHP_OPCACHE_ENABLE' => '0'
    'PHP_OPCACHE_REVALIDATE_FREQ' => '0'
    'PHP_OPCACHE_VALIDATE_TIMESTAMPS' => '0'
    'XDEBUG_SESSION' => 'PHPSTORM'
    'PHP_IDE_CONFIG' => 'serverName=4.craft.test'
    'XDEBUG_CONFIG' => 'client_host=host.docker.internal client_port=9003'
    'XDEBUG_MODE' => 'develop,debug'
    'IMAGE_USER' => 'nitro'
    'PHP_VERSION' => '8.0'
    'NVM_VERSION' => '0.38.0'
    'DEBIAN_FRONTEND' => 'noninteractive'
    'HOME' => '/home/nitro'
    'LC_CTYPE' => 'C.UTF-8'
    'SUPERVISOR_ENABLED' => '1'
    'SUPERVISOR_PROCESS_NAME' => 'php-fpm'
    'SUPERVISOR_GROUP_NAME' => 'php-fpm'
    'USER' => 'nitro'
    'HTTP_ACCEPT_ENCODING' => 'gzip'
    'HTTP_X_FORWARDED_PROTO' => 'https'
    'HTTP_X_FORWARDED_FOR' => '172.18.0.1'
    'HTTP_ACCEPT' => '*/*'
    'HTTP_USER_AGENT' => 'curl/7.79.1'
    'HTTP_HOST' => '4.craft.test'
    'SCRIPT_FILENAME' => '/app/web/index.php'
    'REDIRECT_STATUS' => '200'
    'SERVER_NAME' => ''
    'SERVER_PORT' => '80'
    'SERVER_ADDR' => '172.18.0.12'
    'REMOTE_USER' => ''
    'REMOTE_PORT' => '44484'
    'REMOTE_ADDR' => '172.18.0.19'
    'SERVER_SOFTWARE' => 'nginx/1.18.0'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'REQUEST_SCHEME' => 'http'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'DOCUMENT_ROOT' => '/app/web'
    'DOCUMENT_URI' => '/index.php'
    'REQUEST_URI' => '/'
    'SCRIPT_NAME' => '/index.php'
    'CONTENT_LENGTH' => ''
    'CONTENT_TYPE' => ''
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1649957152.8935
    'REQUEST_TIME' => 1649957152
    'DEFAULT_SITE_URL' => 'https://4.craft.test/'
    'CRAFT_ENVIRONMENT' => 'dev'
    'CRAFT_SECURITY_KEY' => 'tmp'
    'CRAFT_DEV_MODE' => '1'
    'CRAFT_DB_DATABASE' => 'craft4_dev'
    'CRAFT_DB_USER' => 'nitro'
    'CRAFT_DB_PASSWORD' => 'nitro'
    'CRAFT_DB_DRIVER' => 'pgsql'
    'CRAFT_DB_SCHEMA' => 'public'
    'CRAFT_DB_SERVER' => 'postgres-13-5432.database.nitro'
]  {"ip":"172.18.0.1"}
```

With `components.log.monologTargetConfig.allowLineBreaks` set to `false`

```
[2022-04-14T17:22:09+00:00] web.INFO: Opening DB connection: pgsql:host=postgres-13-5432.database.nitro;dbname=craft4_dev;port=5432 {"trace":[],"memory":9626400,"category":"yii\\db\\Connection::open"} 
[2022-04-14T17:22:09+00:00] web.INFO: Request context  {"ip":"172.18.0.1","vars":{"_GET":[],"_POST":[],"_COOKIE":[],"_FILES":[],"_SERVER":{"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","HOSTNAME":"4.craft.test","PHP_DISPLAY_ERRORS":"on","PHP_MEMORY_LIMIT":"512M","PHP_MAX_EXECUTION_TIME":"5000","PHP_UPLOAD_MAX_FILESIZE":"512M","PHP_MAX_INPUT_VARS":"5000","PHP_POST_MAX_SIZE":"512M","PHP_OPCACHE_ENABLE":"0","PHP_OPCACHE_REVALIDATE_FREQ":"0","PHP_OPCACHE_VALIDATE_TIMESTAMPS":"0","XDEBUG_SESSION":"PHPSTORM","PHP_IDE_CONFIG":"serverName=4.craft.test","XDEBUG_CONFIG":"client_host=host.docker.internal client_port=9003","XDEBUG_MODE":"develop,debug","IMAGE_USER":"nitro","PHP_VERSION":"8.0","NVM_VERSION":"0.38.0","DEBIAN_FRONTEND":"noninteractive","HOME":"/home/nitro","LC_CTYPE":"C.UTF-8","SUPERVISOR_ENABLED":"1","SUPERVISOR_PROCESS_NAME":"php-fpm","SUPERVISOR_GROUP_NAME":"php-fpm","USER":"nitro","HTTP_ACCEPT_ENCODING":"gzip","HTTP_X_FORWARDED_PROTO":"https","HTTP_X_FORWARDED_FOR":"172.18.0.1","HTTP_ACCEPT":"*/*","HTTP_USER_AGENT":"curl/7.79.1","HTTP_HOST":"4.craft.test","SCRIPT_FILENAME":"/app/web/index.php","REDIRECT_STATUS":"200","SERVER_NAME":"","SERVER_PORT":"80","SERVER_ADDR":"172.18.0.12","REMOTE_USER":"","REMOTE_PORT":"44474","REMOTE_ADDR":"172.18.0.19","SERVER_SOFTWARE":"nginx/1.18.0","GATEWAY_INTERFACE":"CGI/1.1","REQUEST_SCHEME":"http","SERVER_PROTOCOL":"HTTP/1.1","DOCUMENT_ROOT":"/app/web","DOCUMENT_URI":"/index.php","REQUEST_URI":"/","SCRIPT_NAME":"/index.php","CONTENT_LENGTH":"","CONTENT_TYPE":"","REQUEST_METHOD":"GET","QUERY_STRING":"","FCGI_ROLE":"RESPONDER","PHP_SELF":"/index.php","REQUEST_TIME_FLOAT":1649956928.400415,"REQUEST_TIME":1649956928,"DEFAULT_SITE_URL":"https://4.craft.test/","CRAFT_ENVIRONMENT":"dev","CRAFT_SECURITY_KEY":"•••","CRAFT_DEV_MODE":"1","CRAFT_DB_DATABASE":"craft4_dev","CRAFT_DB_USER":"nitro","CRAFT_DB_PASSWORD":"•••••","CRAFT_DB_DRIVER":"pgsql","CRAFT_DB_SCHEMA":"public","CRAFT_DB_SERVER":"postgres-13-5432.database.nitro"}}}
```

### CODE REVIEW

**Comment by timkelty** [comment]
Github isn't letting me edit the desc

**Comment by timkelty** [comment]
Github isn't letting me edit the description, but:
- SQL queries are now logged as `Craft::debug`, meaning they won't be logged by default in `devMode`.

**Comment by khalwat** [comment]
> Remove DbConfig::enableProfiling, DbConfig::enableLogging

Man. I just added these... 😄

**Comment by timkelty** [comment]
@khalwat keep your pants on. You can still configure them. I'll include examples.

**Comment by khalwat** [comment]
Are you planning to add back in the rather useful method context that was in Craft 3 logs?

Craft 3:
```
2022-04-13 12:15:22 [-][1][-][info][yii\db\Connection::open] Opening DB connection:
```
Craft 4:
```
[2022-04-08T19:05:09.197562+00:00] web.INFO: Opening DB connection:
```

That lack of method context is pretty important to me when looking at log files. Also would love it if changes to the log file format (e.g.: `web.ERROR` instead of `[error]`) weren't done arbitrarily.

Not sure why listing the log file in the log file is useful, except maybe for streamed logs where everything is combined? If that's the reasoning, could I suggest instead: `[web][error]`? I think the old Yii2 formatting method of separating categories in `[]`s was. more readable.

**Comment by timkelty** [comment]
> Are you planning to add back in the rather useful method context that was in Craft 3 logs?

What you're referring to is the `category` (which is often logged as `__METHOD__`). That is there in the Craft 4, at the end of the message:

```
[2022-04-14T17:22:09.232670+00:00] web.INFO: Opening DB connection: pgsql:host=postgres-13-5432.database.nitro;dbname=craft4_dev;port=5432 {"trace":[],"memory":9626400,"category":"yii\\db\\Connection::open"} ```

You were likely missing it before because I was erroneously adding all the global vars there too.

> Also would love it if changes to the log file format (e.g.: web.ERROR instead of [error]) weren't done arbitrarily.

Not arbitrary. What you're seeing is Monolog's default formatter: [`LineFormatter::SIMPLE_FORMAT`](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Formatter/LineFormatter.php#L27)

While you can easily change this by setting in `config/app.php` `components.log.monologTargetConfig.formatter` to whatever you want, I'd probably recommend just "getting used to it", if your changes are superficial-ish.

**Comment by timkelty** [comment]
@brandonkelly when you review, can you look at the `TODO` line here: https://github.com/craftcms/cms/blob/fdb540bfed6e25ffc171db76d6b7d5e8c79eea78/src/log/Dispatcher.php#L83-L85

It was taken verbatim from https://github.com/craftcms/cms/blob/develop/src/queue/QueueLogBehavior.php#L99-L102, but wasn't 💯 sure what the purpose was.

**Comment by brandonkelly** [comment]
@timkelty The Craft 3 comment says `Prevent verbose system logs` so guessing it’s something to do with that? Maybe try comparing what the queue logs look like with/without it.

**Pull request merged**
