### PR TITLE
Migration Installation

### PR DESCRIPTION
**Pull request by markhuot**
This takes the (currently) web-only install controller and copies it over into a console controller. With this you can install Craft with a simple `./craft migrate/install`. For CI testing I'd love to not have to bundle a SQL dump with my repo just to get a fresh instance spun up.

```bash
$ ./craft migrate/install --email=foo@example.com --username=admin --siteName="Test Site" --siteUrl="http://localhost" --siteLangcode=en --password=foobar
Yii Migration Tool (based on Yii v2.0.12)

    > create table {{%assetindexdata}} ... done (time: 0.022s)
    > create table {{%assets}} ... done (time: 0.013s)
    > create table {{%assettransformindex}} ... done (time: 0.016s)
    > ...
    > create index assetindexdata_sessionId_volumeId_idx on {{%assetindexdata}} (sessionId,volumeId) ... done (time: 0.016s)
    > create index assetindexdata_volumeId_idx on {{%assetindexdata}} (volumeId) ... done (time: 0.014s)
    > create unique index assets_filename_folderId_unq_idx on {{%assets}} (filename,folderId) ... done (time: 0.010s)
    > ...
    > add primary key searchindex_elementId_attribute_fieldId_siteId_unq_idx on {{%searchindex}} (elementId,attribute,fieldId,siteId) ... done (time: 0.015s)
    > add foreign key assetindexdata_volumeId_fk: {{%assetindexdata}} (volumeId) references {{%volumes}} (id) ... done (time: 0.022s)
    > add foreign key assets_folderId_fk: {{%assets}} (folderId) references {{%volumefolders}} (id) ... done (time: 0.020s)
    > ...
    > populate the info table ... done
    > save the first user ... done
    > save the email settings ... done
Test CraftQL was successfully installed.
```

### CODE REVIEW

**Comment by brandonkelly** [comment]
Thanks Mark!! Will review and get back to you.

**Comment by markhuot** [comment]
Thanks. Feel free to close this and go your own way. I just wanted to 1.) make the feature request and 2.) see if it was even possible, it definitely is.

**Comment by brandonkelly** [comment]
Merged into `develop`! cf3f9a88f4db94a76d53def6e78ad26f2edb7757

**Comment by markhuot** [comment]
😱 

Off I go rewrite my Travis scripts ([travis-ci.org/markhuot/craftql](https://travis-ci.org/markhuot/craftql))!

**Pull request merged**
