### PR TITLE
Add asset indexing to Craft cli.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Closes https://github.com/craftcms/cms/issues/2980.

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
I actually think the default should be `false` (`0`) on `$cacheImages` here, but since the GUI default is `true`, I made the default `true` here as well. I'm guessing a lot of people don't want to fill their database with an image they are already storing somewhere else (like on an S3 bucket).

**Comment by brandonkelly** [comment]
They get stored in the `storage/` folder, not your database, and it’s a prerequisite to generating new image transforms, so a reasonable argument could be made either way.

**Comment by andris-sevcenko** [comment]
Sorry for the delayed response - thinks have been a tad hectic lately.

Can you, please, reduce the same indexing session id for one indexing session instead of generating a new one for every file that is getting indexed?

**Comment by ryanpcmcquen** [comment]
@andris-sevcenko, thank you for reviewing this! How would you recommend doing that? Can it just use a timestamp?

**Comment by andris-sevcenko** [comment]
@ryanpcmcquen you should call the `Craft::$app->getAssetIndexer()->getIndexingSessionId()` method once per session and use the returned value for all actual indexing calls.

Also, the docblock above the class definition does not look like anything that Craft has. ([starting here](https://github.com/craftcms/cms/pull/3595/files#diff-32af748b77d508e466862f9008ecd96fR18))

**Comment by ryanpcmcquen** [comment]
@andris-sevcenko, isn't this similar?
https://github.com/craftcms/cms/blob/3.1/src/console/controllers/MigrateController.php#L24

I changed it to use the session id as requested. 🎉

**Comment by ryanpcmcquen** [comment]
@andris-sevcenko, I will restore it then! Anything else?

**Comment by ryanpcmcquen** [comment]
@andris-sevcenko, I restored the docblock, any other comments on the PR?

**Comment by andris-sevcenko** [comment]
@ryanpcmcquen ah sorry, totally forgot about this one today - it was on my list, too :/

I'll take care of this tomorrow my time, sorry for the delay!

**Comment by andris-sevcenko** [comment]
Thank you for your patience, Ryan. You have been more than awesome!

**Comment by ryanpcmcquen** [comment]
Thank you Andris!

**Comment by khalwat** [comment]
Wow, thank you @ryanpcmcquen -- saved me from writing it!

**Comment by ryanpcmcquen** [comment]
@brandonkelly, should I have set the `@author` in the docblock? Wasn't sure what the policy was here ...

**Pull request merged**
