### PR TITLE
Bump @craftcms/vue `1.0.1`

### PR DESCRIPTION
**Pull request by nfourtythree**

### CODE REVIEW

**Comment by brandonkelly** [comment]
Shouldn’t this include a new `package-log.json` and built Vue assets?

**Comment by nfourtythree** [comment]
Nope, this package is simply a collection of Vue source components for inclusion within other assets.

**Comment by brandonkelly** [comment]
Right but then won’t those other assets need to be rebuilt?

**Comment by nfourtythree** [comment]
They were already rebuilt in the other PR. Because they use relative paths. After our decisions the other day in the future this will all be in one PR

**Pull request merged**
