### PR TITLE
Fixed using CRAFT_FRAMEWORK_PATH for including framework files in console file

### PR DESCRIPTION
**Pull request by bertoost**
For dev installations with vendor files etc.

This way you can create a "console" PHP file in your dev installation root, the same way as for the web index.php file, setting some constants.

```php
#!/usr/bin/env php
<?php

define('CRAFT_BASE_PATH', __DIR__ . '/craft/');
define('CRAFT_VENDOR_PATH', dirname(__DIR__) . '/craft_git/vendor/');
define('CRAFT_FRAMEWORK_PATH', CRAFT_VENDOR_PATH . 'yiisoft/yii/framework/');

require CRAFT_BASE_PATH . 'app/etc/console/yiic.php';
```

### CODE REVIEW

**Comment by brandonkelly** [comment]
Thanks!

**Comment by bertoost** [comment]
Hmm now trying (for the first time) to use migration command, getting this error;

```
Fatal error: Class 'MigrateCommand' not found in /path/to/my/craft/checkout/src/consolecommands/MigrateCommand.php on line 50
```

Probably he doesn't know about Yii's Migrate Command where Craft's version extends from. Any idea?

**Comment by brandonkelly** [comment]
@bertoost Is Craft symlinked in your project?

**Comment by bertoost** [comment]
Yes it is. Since my develop installation uses the Git checkout (for cases if I need to change core stuff ;-))

**Comment by brandonkelly** [comment]
Yeah that’s probably the issue. You may need to set additional constants to help Craft bootstrap itself. Been a while since I dealt with it though so don’t remember exactly what to do.

**Comment by bertoost** [comment]
Did not yet figured it out.. Decided to change the app folder again from a symlinked-git version to a normal one and everything works again. Hopefully you can remember it some day ;-)

**Pull request merged**
