### PR TITLE
Consolidated “Licensing Issues” alert

### PR DESCRIPTION
**Pull request by brandonkelly**
Consolidates most licensing issues into a single alert, which lists each of the issues and displays a “Resolve now” link, which will take the user (admin or not – doesn’t matter) to Craft Console, with a fresh cart loaded with line items to resolve each of the issues.

The new “Licensing Issues” alert

### CODE REVIEW

**Comment by gglnx** [comment]
@brandonkelly Tried to upgrade to `4.4.0-beta.5` and I get the following migration error:

```
➜ ./craft migrate/all --no-content --interactive=0 --no-backup
Checking for pending Craft and plugin migrations ...
Total 1 new Craft migration to be applied:
    - m230226_013114_drop_plugin_license_columns

*** applying m230226_013114_drop_plugin_license_columns
Exception: 3 arguments are required, 2 given (vendor/craftcms/cms/src/migrations/m230226_013114_drop_plugin_license_columns.php:22)
#0 vendor/craftcms/cms/src/migrations/m230226_013114_drop_plugin_license_columns.php(22): sprintf('alter table %s ...', '{{%plugins}}')
#1 vendor/craftcms/cms/src/db/Migration.php(49): craft\migrations\m230226_013114_drop_plugin_license_columns->safeUp()
#2 vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#3 vendor/craftcms/cms/src/console/controllers/MigrateController.php(358): yii\console\controllers\BaseMigrateController->migrateUp('m230226_013114_...')
#4 [internal function]: craft\console\controllers\MigrateController->actionAll()
#5 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#7 vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#8 vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('all', Array)
#9 vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#10 vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#11 vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#12 vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#13 vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#15 craft(15): yii\base\Application->run()
#16 {main}
*** failed to apply m230226_013114_drop_plugin_license_columns (time: 0.021s)
```

**Comment by gglnx** [comment]
```php
$this->execute(sprintf('alter table %s drop constraint %s', Table::PLUGINS, '{{%plugins_licenseKeyStatus_check}}'));
```

This repairs it.

**Comment by brandonkelly** [comment]
Thanks for reporting! Fixed now in 3.8.0-beta.5 and 4.4.0-beta.6.

**Comment by brandonkelly** [comment]
Previously those would have been a generic “Plugin licenses have issues!” alert. We’ve stopped doing that, in favor of combining all issues that could be resolved with a purchase (plugin needs to be purchased, renewal needs to be purchased, etc.) into a single alert with a single CTA.

But yes, in the case of a license _mismatch_, individual alerts with individual CTAs will still be displayed, because you will need to take manual action for each one. Or maybe you just need to swap out your `config/license.key` file with the one that those licenses are actually associated with.

**Comment by shoored** [comment]
> Thanks for reporting! Fixed now in 3.8.0-beta.5 and 4.4.0-beta.6.

Hello, trying to update from `3.7.65` to latest `3.8.9` returns the same error. It looks like the fix did not make it into the 3.8 migration?

I'm also on Postgres.

**Comment by brandonkelly** [comment]
@shoored The fix was initially made for 3.8.0-beta.5. Can you post the exact error you’re getting along with the stack trace, pulled from your logs in `storage/logs/`?

**Comment by shoored** [comment]
@brandonkelly Sure thing, this is the error:

```
*** applying m230226_013114_drop_plugin_license_columns
    > execute SQL: alter table {{%plugins}} drop constraint {{%plugins_licenseKeyStatus_check}} ...Exception: SQLSTATE[42704]: Undefined object: 7 ERROR:  constraint "plugins_licenseKeyStatus_check" of relation "plugins" does not exist
The SQL being executed was: alter table "plugins" drop constraint "plugins_licenseKeyStatus_check" (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'alter table "pl...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('alter table "pl...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Migration.php(219): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/migrations/m230226_013114_drop_plugin_license_columns.php(22): yii\db\Migration->execute('alter table {{%...')
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(53): craft\migrations\m230226_013114_drop_plugin_license_columns->safeUp()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(386): yii\console\controllers\BaseMigrateController->migrateUp('m230226_013114_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 /var/www/html/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#14 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(212): yii\base\Controller->run('migrate/all', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(58): craft\console\Controller->run('migrate/all', Array)
#17 [internal function]: craft\console\controllers\UpController->actionIndex()
#18 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#20 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('', Array)
#21 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(221): yii\console\Controller->runAction('', Array)
#22 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#23 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#24 /var/www/html/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('up', Array)
#25 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#26 /var/www/html/vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest(Object(craft\console\Request))
#27 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#28 /var/www/html/craft(26): yii\base\Application->run()
#29 {main}
*** failed to apply m230226_013114_drop_plugin_license_columns (time: 0.050s)
```

There is only a `console.log` file in `storage/logs` but there does not seem to be any mention of a stack trace or errors in that file unfortunately.

**Comment by brandonkelly** [comment]
> I just checked the actual migration file and the fix mentioned does not appear in that file 🤷‍♂️

As in you’re seeing

```php
$this->execute(sprintf('alter table %s drop constraint {{%plugins_licenseKeyStatus_check}}', Table::PLUGINS));
```

instead of 

```php
$this->execute(sprintf('alter table %s drop constraint %s', Table::PLUGINS, '{{%plugins_licenseKeyStatus_check}}'));
```

?

Maybe try nuking your `vendor/` folder and running `composer update`?

**Comment by shoored** [comment]
Meh, sorry, I misread the migration file changes in the fixed commit. That file is indeed correct. 

The error persists unfortunately. But I'm replying to a pull request so I will create a new issue. It's probably something to do with this specific database since the constraint does not exist.

**Pull request merged**
