### PR TITLE
Nested element workflow improvements

### PR DESCRIPTION
**Pull request by brandonkelly**
### Description

When saving a nested element within a Matrix/Addresses field in card view, the changes are now saved to a draft of the owner element, rather than published immediately. The changes won’t actually go live until the owner element is saved. If the draft is discarded, the changes will be discarded too.

Nested element cards that contain unpublished edits identify themselves with a blue modified indicator. (Newly-added nested elements have a similar indicator too, now.)

https://github.com/user-attachments/assets/b2dbb210-0b5c-46b3-9b2e-3fed4023a766

This **only** affects Matrix/Addresses fields in cards view. Decided to keep element index view working as-is, since that view is more obviously dealing with separate elements that aren’t really “part of” the owner element’s content, like card view is.

CKEditor will be updated for consistency with these changes, as well.

### Related issues

- #14286
- #14603
- #14727
- #15956
- #16039
- #15713

### CODE REVIEW

**Comment by mark-reason** [comment]
I'm still having the same issue on version 5.5.2.

You can see the difference in the following videos. The first has the field set as an inline editable block and the draft changes are reflected in the preview, however in the second video I've got the field set as a card but the changes don't show until I click save at which point they are now published.

https://github.com/user-attachments/assets/ad484c98-ee6d-43b8-90eb-a13e421f6e6a

https://github.com/user-attachments/assets/0bb1ce2c-1d43-490e-af2d-bc9999f5676b

**Comment by brandonkelly** [comment]
@mark-reason It’s expected that Live Preview won’t reflect your changes until you press Save, however the change in 5.5.0 is supposed to be that pressing Save doesn’t actually publish the changes immediately. The only known exception to that is when editing an element type that doesn’t support drafts, like global sets. What is the parent element type you’re editing here?

**Comment by mark-reason** [comment]
It was a matrix field within an entry type. It definitely looks to be publishing the changes straight away, see the video with graphql query after.

https://github.com/user-attachments/assets/448d90ec-4ede-46cb-b2eb-f145fbc95f30

**Comment by brandonkelly** [comment]
@mark-reason Doh, looks like it only worked when you open the editor slideout by double-clicking on the card. I never tested going through the “Edit” action menu item.

Fixed for the next release via cf41c5f0de3018bb590b27d0ebb8371e4af83ef0.

**Comment by brandonkelly** [comment]
@mark-reason Craft 5.5.4 is out with that fix. Thanks again!

**Comment by Michael-Paragonn** [comment]
@brandonkelly I see you mention both the cards view and the element index view; what about the inline-editable blocks view? 
image

(EDIT: Posted a [separate issue here](https://github.com/craftcms/cms/issues/17062))

**Pull request merged**
