### PR TITLE
add an example of saving an element with afterSave

### PR DESCRIPTION
**Pull request by sbatson5**
## What's in this PR?

I've been working on my first Craft Plugin with no prior experience, and there have been a couple hiccups.  For Elements, it wasn't very apparent to me immediately when `afterSave()` came into play and whether it was something I needed to handle myself.  I think having one quick blurb about how to save an element along with the explanation of `afterSave()` could be useful.  Otherwise, a new dev doesn't quite get when this comes into play and they've done a lot of setup with knowing how to execute it.

### CODE REVIEW

**Comment by brandonkelly** [comment]
@sbatson5 Thanks for the PR! Does GitHub give you the ability to allow me to edit the PR code?

**Comment by sbatson5** [comment]
@brandonkelly I could probably set you as an owner of the forked repo, but that workflow would seem a bit odd. I'm happy to make edits if you want to leave a review on the line or point me in the right direction.

**Comment by brandonkelly** [comment]
@sbatson5 I know when you first create a PR, GitHub will give you the option, just for the PR branch. Just not sure if it’s possible to change that setting once the PR has already been created. If not, can you close the PR and recreate, with that option enabled?

**Comment by sbatson5** [comment]
This has been checked since I opened the PR @brandonkelly.  Are you not able to edit?

Can I ask what changes you are looking to make?

Screen Shot 2019-04-26 at 8 30 47 PM

**Comment by brandonkelly** [comment]
Sorry, not sure why the edit button wasn't showing up in the pull request page like it usually is, but I was able to edit it directly on your repo. All merged now! Thanks again for the PR

**Pull request merged**
