### PR TITLE
Notification redesign

### PR DESCRIPTION
**Pull request by brandonkelly**
### Description

Control panel user notifications have been redesigned to stack up from the bottom-left of the window, with a cleaner and more accessible design.

An “Entry saved” notification, with a link to the entry.

There are several additional improvements:

- The duration is now 5 seconds by default, and there’s a new “Notification Duration” user preference where users can customize that to their liking.

The new “Notification Duration” user preference, with the options “2 seconds”, “5 seconds”, “10 seconds”, and “Show them indefinitely”.

- If the browser tab isn’t visible when a notification is first shown, the timeout won’t start until the tab becomes visible.
- If a notification is hovered over by the cursor, the timeout will pause and restart on mouse-out.
- If a notification is clicked on, the timeout will be cancelled altogether.
- Notifications can be manually closed via the Close button at any time.
- Notifications can include additional details, links, or buttons, depending on the context.
- Success notifications can now distinguish themselves from neutral “notices” by calling `Craft.cp.displaySuccess()` instead of `Craft.cp.displayNotice()`.

We are taking advantage of the additional details in two ways currently:

- When elements are saved, a link to the element will be included.
- Dashboard widget delete notifications now include an “Undo” button, which will create a new widget with the same settings as the deleted widget. (This replaces the need for a delete confirmation.)

A “Widget deleted” notification, with an “Undo” button

### Related issues

- #7142
- #11573

### CODE REVIEW

**Review by gcamacho079 — CHANGES_REQUESTED** [review]
I made a couple smaller tweaks after testing on VoiceOver. Some other changes that should be made are:

### Focus Management
- If there's an interactive element in the (like undo button), `tabindex="-1"` should be added to the new `.notification` container, focus should be moved to it, and the duration timeout should pause while focus is on or inside the container.
- If the text content overflows and adds scrollbars, `tabindex="-1"` should be added to the `.notification` container and focus should be moved to it. This will allow keyboard users to scroll the content.
- When the notification closes via ESC keypress inside the container, interactive element click (i.e. Undo button), or close button keypress, **focus should move to the previously-focused element on the page**.

### Other
Something to look into in the future would be a place in the control panel where users can go and review previous toast messages; this would be a benefit for users with short term memory loss, or who might otherwise miss or accidentally dismiss messages.

**Comment by tomkiss** [comment]
Excellent notifications update - Well done everyone! 🙌

**Comment by thijskaspers** [comment]
@brandonkelly Is there an option to change the position of the notification that pops up?

We've gotten client feedback that they "Saved" a page in the CP, but don't see the changes on the front-end. What actually happened was, they forgot to fill in a required field, but it wasn't clear to them.

If you work on a larger monitor and click on "Save" top right of the screen, you can easily miss the "Couldn't save entry" notification at the bottom left of the screen, that isn't where your focus is after clicking save top-right.

We agree that bottom left is the nicest position and less intrusive, but for less tech-savy clients it would be better in our opinion to have the option to place it top-center.... or: Make it more clear that something went wrong, make the Tab with the exclamation icon 'red'? Add an additional error text? Scroll down to the first error after save? Something like that.

**Comment by brandonkelly** [comment]
@thijskaspers We are looking into introducing an error summary at the top of the page, which should help. You can also point your clients to the “Notification Duration” setting in their user account preferences, which they can set to a longer duration or have them display indefinitely.

**Comment by brandonkelly** [comment]
(If you still want to advocate for a “Notification Position” preference, please open a new discussion about it.)

**Comment by thijskaspers** [comment]
> 

Nah, an error summary at the top of the page sounds like a good solution, to make it more clear there were validation errors for 1 or more fields.

**Comment by brandonkelly** [comment]
@thijskaspers For posterity, Craft 4.5.0 was released today, with the new validation error summary pane.

**Comment by thijskaspers** [comment]
> @thijskaspers For posterity, Craft 4.5.0 was released today, with the new validation error summary pane.

Awesome! Nice improvement, I think clients will like it, thanks!

**Pull request merged**
