### PR TITLE
Add a Twig function to create yii\db\Expression objects

### PR DESCRIPTION
**Pull request by carlcs**
Sometimes it’s not possible to pass a db expression as a string, becaus Yii escapes it and generates invalid SQL. https://github.com/yiisoft/yii2/issues/553

Example use of the function:

```twig
{% set ids = [1639, 2079] %}

{% set orderByParam = ids ?
    dbExpression('FIELD(elements.id, ' ~ ids|reverse|join(', ') ~ ') desc, title asc') :
    'title asc' %}

{% set query = craft.entries
    .limit(50)
    .orderBy(orderByParam) %}
```

### CODE REVIEW

**Comment by brandonkelly** [comment]
I like this. Can you rename the function to `expression()` instead of `dbExpression()` though?

**Comment by brandonkelly** [comment]
(Worth noting that your particular example could also be achieved using the [fixedOrder](https://docs.craftcms.com/v3/dev/element-queries/entry-queries.html#fixedorder) param though.)

**Comment by carlcs** [comment]
@brandonkelly `fixedOrder` only works when using it in combination with `ids()` though. In this example the `ids` variable is an array of element IDs for entries that should show up first, but there are more entries returned.

**Comment by carlcs** [comment]
```twig
{% set ids = blog.featuredBlogEntries.ids() %}
```
This makes the example clearer.

**Comment by brandonkelly** [comment]
Ah gotcha, thanks for clarification! Though I realize expressions could be used for a variety of things so wouldn't have declined the PR anyway :)

**Pull request merged**
