### PR TITLE
allowing more granular configurations for 'appType'

### PR DESCRIPTION
**Pull request by nateiler**
For example, this would allow a console app to specify it's own configuration independently of web app or rest app (ahem).

### CODE REVIEW

**Comment by nateiler** [comment]
Wanted to get some thoughts around this.  The idea is`config/app.php` is a global configuration override yet allow for more granular overrides.  This is particularly helpful when configuring a REST app which commonly requires different component configurations than the main Craft web app.

**Comment by brandonkelly** [comment]
I don’t really want to support alternative `appType` values, since they are meant to represent the two ways PHP could be invoked (via web server or CLI); not necessarily how the request should behave.

That said, I know you have a legit reason for needing to provide REST request-specific configs and you need to use a different Application class, so I’ve just made that possible with 27fa2e7f09ba7d551033946c4a76271162952fed.

You will still need to define your main application config via `config/app.php`, but that file could itself just load a more specific config file depending on request type. For example if you have a REST-specific entrypoint PHP file, you could define a PHP constant from it:

```php
define('REST_REQUEST', 1);
```

And then from `config/app.php`:

```php
if (defined('REST_REQUEST')) {
    return require(__DIR__.'/rest.php');
}

// ...
```

And now, that config file could override the actual Application class like this:

```php
return [
    'class' => custom\rest\Application::class,
    // ...
];
```

**Comment by narration-sd** [comment]
❤️ for approach, 👍 for method...

**Comment by nateiler** [comment]
Thanks Brandon.  I think this will work perfectly...although we’re not needing to define a separate application any longer, it’s nice to know it’s available.

**Pull request closed without merging**
