### PR TITLE
Add block.getType().handle to matrixblock class

### PR DESCRIPTION
**Pull request by leevigraham**
Adds a new class as a styling hook for third party addons.

It would be great if this was back ported to v2.

### CODE REVIEW

**Comment by brandonkelly** [comment]
This is a duplicate of #1915.

**Comment by leevigraham** [comment]
@brandonkelly, Any chance of getting this backported to v2? I guess we can target styling via an attribute selector. A class would be more obvious tho.

**Comment by brandonkelly** [comment]
Yeah can backport to v2. Seems a little sketchy to add a class based on a user-defined handle, even if it had a `type-` prefix or something, so I think I prefer the `data-type` attribute.

**Comment by brandonkelly** [comment]
Done for the next v2 release: ca9499251f94c6d81bf64f6203a30706828fdb69

**Pull request closed without merging**
