### PR TITLE
Add the impersonateUsers User permission

### LINKED ISSUE #1186: Add impersonation user permission
> Created by: Anonymous (gijs@itmundi.nl) on 2015/03/16 11:59:50 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

Currently only super admins are able to use impersonate, but its also useful to other users.

### PR DESCRIPTION
**Pull request by gtettelaar**
Doh! Of all things, I didn't test #4401 via the CP - I changed the permission check in `actionEditUser()` to reflect the new permission so that the `Login as {user}` dropdown option is visible. Sorry bout that! 

Of what I can see `craft\web\User` has two references to the Impersonate functionality: `Line 306` & `Line 406` but they both deal with "If a user is using Craft whilst impersonating someone" not "Is this user allowed to impersonate other users" the latter is where this permission makes changes.

Resolves #1186

### CODE REVIEW

**Comment by brandonkelly** [comment]
We should also limit user impersonation to users with less permissions than the current user, OR once you’re logged in as that user, factor in the real user’s permissions when doing permission checks. Otherwise this could introduce a permission escalation vector. (All it would take is being granted this one permission, and you basically become an admin, because you could impersonate an admin, and then grant yourself admin status, or start doing things you’re generally not permitted to do, etc.)

**Comment by gtettelaar** [comment]
> We should also limit user impersonation to users with less permissions

+1.
 
In `craft\elements\User::can()` I can implement an additional check to ensure the user is not punching above their weight when doing something through an impersonated session. 

It's probably also worth forcing admins who assign this permission to limit the assigned impersonation rights to users in specific user groups. So that the default is not _all_ users. (I.E. An editor can only impersonate people in the `authors` group e.t.c.). Just to restrict it a little bit further.
 
I'll finish this over the weekend for you to have a look at and drop a message once it's done. I'll label the PR as [WIP]. Thanks! @brandonkelly

**Comment by brandonkelly** [comment]
> It's probably also worth forcing admins who assign this permission to limit the assigned impersonation rights to users in specific user groups. So that the default is not all users. (I.E. An editor can only impersonate people in the authors group e.t.c.). Just to restrict it a little bit further.

I don’t think we need to worry about user _groups_ at all, just permissions.

When determining if User A should be allowed to impersonate User B, we should check the following:

- If User A is an admin, then we can immediately determine that they’re allowed and skip other checks.
- If User B is an admin (and User A isn’t), they are disallowed.
- If User A doesn’t have the `impersonateUsers` permission, they are disallowed.
- If User A doesn’t have all the same permissions as User B (whether granted directly or via user groups), they are disallowed.
- Otherwise, they are allowed.

> Coincidentally this would also resolve #3501

Thanks for bringing that one up, I didn’t realize there were two issues asking for basically the same thing. Just closed #1186 in favor of #3501. (And the user groups thing was just a suggestion in #3501. If we implement this based on permissions only, it will still be resolved.)

**Comment by gtettelaar** [comment]
That's a fair point. Removing the user groups from the equation makes this easier for me to implement. The permission check will resolve any "security" concerns. 

That's not really why I liked the user group based assignment though- I found the linking to user group an elegant way to **force** admins to be explicit when assigning this permission. Albeit the same result can be achieved by adding a warning in the `UserPermissions` class under the `impersonateUsers` permission explaining what this permission does (Similar to how `administrateUsers` does it). I was more focused on awareness of what this permission does.

As said, I have an idea to get this implemented into the 3.2 base. Will finish that today or tomorrow and explain it once done.

**Comment by gtettelaar** [comment]
Looks like it's done.

`craft\services\UserPermissions::isImpersonationAllowed()` is used by `UsersController` in `actionEditUser()` and `actionImpersonate()` as a gatekeeper method. It checks all the above rules. 

Furthermore `craft\web\User` is edited so that `checkPermission()` takes into account the permissions of the impersonating user (if there is one). Also i removed a `->admin()` call in d187ca7a97295129b59860a091e9ac4e9267a4aa - this additional query parameter did not make sense if we are allowing non-admin impersonation. 

`craft\services\UserPermissions::doesFirstUserHaveMorePermissions()` is the check to ensure that the _impersonatee_ **cannot** have more permissions than the _impersonator_ but the _impersonator_ **can** have more permissions than the _impersonatee_.

I tested it locally and it looks to work as expected with the permission matching being enforced as expected. Can you confirm this? @brandonkelly

**Comment by brandonkelly** [comment]
> Furthermore `craft\web\User` is edited so that `checkPermission()` takes into account the permissions of the impersonating user (if there is one).

I know I suggested that as one of the possibilities to prevent permission escalation, but we shouldn’t do it. When you are impersonating a user, the whole experience should be identical to the other user’s, including permission enforcement.

**Comment by gtettelaar** [comment]
> I know I suggested that as one of the possibilities to prevent permission escalation, but we shouldn’t do it. When you are impersonating a user, the whole experience should be identical to the other user’s, including permission enforcement.

That change wouldn't make that much difference to the experience - as the permissions should overlap based on earlier checks. With that in mind, there's no real reason to keep it either. Removed it.

**Comment by brandonkelly** [comment]
Ah I misunderstood what you meant; I thought it was only checking the original user in case of impersonation, rather than as an additional check. But yeah, no real reason  to do it, we can trust the session.

**Comment by brandonkelly** [comment]
@gtettelaar so is this PR good to go, or still working on it?

**Comment by gtettelaar** [comment]
@brandonkelly It's ready If you're happy with it. I removed the two chunks in the `craft\web\User` as you asked. 

Took a little more time to get across the line but thanks for the input!

**Comment by michaelrog** [comment]
> If User A doesn’t have all the same permissions as User B (whether granted directly or via user groups), they are disallowed.

Is it necessary to make sure A has _all_ of B's permissions?

What if `craft\web\User::checkPermission()` could check whether the user is being "impersonated" and, if so, return positively only if _both_ both the user and impersonator have the given permission?

**Comment by gtettelaar** [comment]
@michaelrog That was added in fc6eeac7d808f3bdd1a5192f53c062d491db4d79 but then removed in d36a1d9aaa6b50c8ce513e091e41b8156de20d69 because of Brandon's [suggestion](https://github.com/craftcms/cms/pull/4403#issuecomment-502193210). Now regardless of whether we keep it in or not. It is probably imperative to ensure that `User A` has all the permissions that `User B` has even if we were to check the permissions in `checkPermission()`. That "having all permissions" check needs to happen before _any_ impersonation session is started.

If we remove the check in `UsersController` that would mean any user who has the `impersonateUsers` permission can impersonate any other non-admin user. Then it would be determined at execution time if the user can actually execute a specific system function like, editing an entry or accessing a plugin. 

That would mean that the experience of a logged in user (`User B`) and an impersonator (`User A`) could vary because `User A` does not have all the permissions that `User B` has - but he can still impersonate him. An example: `User B` would see an `utilities` tab but `User A` would not because he doesn't have any `utility` based permission. 

My guess is that the end result is, certain actions would be visible to `User B` but not to the impersonating `User A` - OR - the impersonating `User B` would see a bunch of `An unknown problem has occurred` messages because of permission problems.

Hope this makes sense?

**Comment by brandonkelly** [comment]
> Is it necessary to make sure A has _all_ of B's permissions?

Yes because if User B can do something User A isn’t allowed to do, you wouldn’t want to give User A the ability to do that thing simply by impersonating User B.

> What if `craft\web\User::checkPermission()` could check whether the user is being "impersonated" and, if so, return positively only if both both the user and impersonator have the given permission?

That’s exactly what d36a1d9aaa6b50c8ce513e091e41b8156de20d69 just reverted. But then you’re not getting a true representation of User B’s experience. Better to just not give User A the option to impersonate User B in the first place.

**Comment by brandonkelly** [comment]
Doh, you beat me to it @gtettelaar :)

**Comment by michaelrog** [comment]
Right, I get the reasons behind the implementation. I'm asking if providing a "true experience" is the point of impersonation, vs the ability to do mutually authorized things on another User's behalf.

I can see it going either way. For example, I've just recently implemented a system where I have low-permissions Support Team users who can impersonate other users on the front-end purely for the purpose of placing Commerce orders on their behalf. In that case, the impersonated user might theoretically have plenty of permissions that the Support Team user doesn't, and that would be moot to the task one wants to perform on behalf of the other.

To be clear, I'm not strongly opinionated about this. I definitely see the benefit of providing a "true experience" of the impersonated user's permissions [or nothing at all]. Just kind of posing it as a gut check. 

In practice, I suspect it would be extremely rare for an impersonating user to not have at least the permissions of the user they are impersonating, so... ¯\_(ツ)_/¯

**Comment by gtettelaar** [comment]
> In practice, I suspect it would be extremely rare for an impersonating user to not have at least the permissions of the user they are impersonating, so... ¯_(ツ)_/¯

Hitting the hammer on the head with that one. 

My inner pragmatist says we should default to the current implementation, BUT. A config setting could be available (defaulting to `false`) which if set to `true ` disables the gatekeeper check in the `UsersController` and enables a point-by-point check done in `checkPermission()`. This would ensure that you can achieve what you want to achieve. Albeit it is an edge case...

Inherently this could cause a quote-on-quote "worse" impersonation experience but it would have to be explicitly enabled and assigned to a user by an admin. That double fail-safe should provide enough insurance in the event there is a need for this feature in a particular "configuration" of Craft.

P.S. 
Im not entirely sold on a global config setting for `impersonateUsers`. @michaelrog Would it be valid to determine this on a user-by-user (or group) case?

**Comment by brandonkelly** [comment]
YAGNI

**Comment by gtettelaar** [comment]
> YAGNI

[He would](https://github.com/craftcms/cms/pull/4403#issuecomment-502254665). 

Regardless, Let's just merge the PR as it is now for `BETA-3` and then if a bunch more people start asking for more fine-grained control over the impersonation permission it can always be added later one way or another.

**Comment by michaelrog** [comment]
> [He would](https://github.com/craftcms/cms/pull/4403#issuecomment-502254665).

Eh, it's a corner's corner case. (I agree with Brandon; YAGNI.)

Switching up flavors of impersonation via a relatively obscure config option is probably not a good experience for the vast majority of customers.

**Comment by gtettelaar** [comment]
> Switching up flavors of impersonation via a relatively obscure config option is probably not a good experience for the vast majority of customers.

+1.
I added the point in response to the low-level support team example - as an idea to support that. The config setting wasn't the best idea  (as the P.S noted). A per user setting could be an option if a bunch of people ask for it but it's not necessary to do it now. 

> @gtettelaar so is this PR good to go, or still working on it?

@brandonkelly It's ready🚀

**Comment by brandonkelly** [comment]
All merged. Thanks @gtettelaar!

**Comment by hubertott** [comment]
Is there an ability to disable **impersonateUsers** at a global level. ie. override the permission at the config level so even Admins of the system cannot impersonate another user? [That is without modifying the codebase]

In the Craft Commerce sense we feel impersonating a user may leads to the ability for someone to make purchases on someone else's behalf. For example if a payment gateway allows you to store an authorisation token for future purchases.

**Comment by brandonkelly** [comment]
You could remove it using the []() event, from a custom module:

```php
use yii\base\Event;
use craft\controllers\UsersController;
use craft\events\RegisterUserActionsEvent;

// ...

Event::on(
    UsersController::class,
    UsersController::EVENT_REGISTER_USER_ACTIONS,
    function(RegisterUserActionsEvent $e) {
        foreach ($e->sessionActions as $i => $action) {
            if ($action['action'] === 'users/impersonate') {
                unset($e->sessionActions[$i]);
            }
        }
    });
```

**Comment by hubertott** [comment]
Thank you for the prompt response.

**Pull request merged**
