### PR TITLE
Enhance composer usage

### PR DESCRIPTION
**Pull request by szepeviktor**
- caching vendor results in an `undefined` state
- composer configuration should be checked

### CODE REVIEW

**Comment by szepeviktor** [comment]
`composer validate`'s exit status is 2, so Travis should stop.

I do not understand why it keeps going.

**Comment by angrybrad** [comment]
@szepeviktor 

> caching vendor results in an undefined state

Where are you seeing this? Removing vendor probably increases the travis build time as well.

> composer validate's exit status is 2, so Travis should stop.

Where are you seeing this as well? It successfully validates so the exit code is 0.

**Comment by szepeviktor** [comment]
> Removing vendor probably increases the travis build time as well.

This is the comment I used to mention
https://github.com/travis-ci/travis-ci/issues/4579#issuecomment-127972205

> It successfully validates so the exit code is 0.

https://travis-ci.com/craftcms/cms/jobs/224140359#L288

> The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update`.

This error sets exit status to 2.

**Comment by angrybrad** [comment]
Thanks!

**Pull request merged**
