### PR TITLE
Log fatal php errors to stream log

### PR DESCRIPTION
**Pull request by timkelty**
This sends fatal PHP errors to `php://stderr` when the app has opted in to `CRAFT_STREAM_LOG`, which is most likely what you want if you've set that.

### CODE REVIEW

**Comment by timkelty** [comment]
@mattstein Probably worth a mention on:
- https://craftcms.com/knowledge-base/locating-error-logs-and-database-backups and 
- https://craftcms.com/docs/3.x/config/#craft-stream-log
- https://craftcms.com/docs/3.x/config/#craft-log-php-errors

**Review by angrybrad — APPROVED** [review]
Looks good to me.

**Comment by angrybrad** [comment]
@timkelty we should add a changelog item for it probably as a bug fix

**Review by jasonmccallister — APPROVED** [review]
💯!!

**Review by brandonkelly — APPROVED** [review]

**Pull request merged**
