### PR TITLE
Fixed redirection when field layout is submitted

### PR DESCRIPTION
**Pull request by nicosomb**
### Description

When we submit the Field layout form, we are redirected to the main settings page. It's not user friendly when you want to do many changes. 

### Related issues

N/A

### CODE REVIEW

**Comment by brandonkelly** [comment]
Thanks for the PR! The `redirect` input isn’t necessary if the URL should stay the same. Just removed it from that page as well as Settings → Users → Settings.

**Comment by nicosomb** [comment]
Thank you @brandonkelly. So, do you want that I update the PR?

**Comment by brandonkelly** [comment]
Sorry to be clear, I’ve already made the change for the next release (0e2e263d0cd17e1954b85f768f1127e0880cc570).

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that change.

**Pull request closed without merging**
