### PR TITLE
#1161 Added event 'userSession.onBeforeAuthenticate'

### PR DESCRIPTION
**Pull request by bertoost**
To let plugins provide alternate CP login features (like ActiveDirectory/LDAP provider)

### CODE REVIEW

**Comment by brandonkelly** [comment]
This is perfect, thanks!

**Comment by bertoost** [comment]
@brandonkelly does this also apply to v3?

**Comment by brandonkelly** [comment]
We ported a similar event to v3 in 439180847bda925325504026dce48877901540d0 – [craft\elements\User::EVENT_BEFORE_AUTHENTICATE](https://docs.craftcms.com/api/v3/craft-elements-user.html#EVENT_BEFORE_AUTHENTICATE-detail).

**Comment by bertoost** [comment]
Cool! Thanks

**Pull request merged**
