### PR TITLE
adjustment for fields with the same label in conditions

### PR DESCRIPTION
**Pull request by i-just**
### Description
Condition builders that show custom fields were not showing all the fields if the fields had the same label. E.g. if you have a custom field named “Toggle” with a handle of `toggle` and another custom field named “Toggle” with a handle of `toggle2`, only one would show in the condition builder.

I changed how we compile a list of options for the condition builder so that the field handle is used as a key for field condition rules. 
I also adjusted how the custom field options are displayed in the menu - they will now show with the field handles (like they do in the field layout builder).

Screenshot 2023-06-09 at 10 09 23

Once a field is selected, it shows as it used to (just with the Label), and if you expand the menu, you can see the handle for it.
Screenshot 2023-06-09 at 10 10 19

### Related issues
#13296

### CODE REVIEW

**Comment by i-just** [comment]
@brandonkelly I just merged `develop` into this PR and re-tested - all good. Could you please have a look for the next release (the issue was raised again)?

**Comment by brandonkelly** [comment]
Handles aren’t meant to be author-facing, so I don’t think we should be surfacing them within element index filters.

Maybe it’s OK for conditions that get stored in the project config (`$this->condition->forProjectConfig`), which should only be viewable by developers, such as within custom element source settings and conditional field settings. Otherwise, I think the current behavior is fine. (If someone has an issue with it, they can rename their fields to be unique.)

**Comment by i-just** [comment]
@brandonkelly, I changed when we show the handle. It’ll show only if you have the `showFieldHandles` preference turned on. I think that has a nice consistency to it. LMK if you’re okay with that or if you’d like to show it only if the condition is for project config.

**Comment by brandonkelly** [comment]
I still think it would be better to only do it for conditions that will be save to the project config. Otherwise it could be a little confusing why some field types are listed sometimes, but not others.

**Comment by i-just** [comment]
It is adjusted so that the handle will only show if `forProjectConfig` is `true` and only if the `showFieldHandles` preference is turned on.

**Comment by brandonkelly** [comment]
On second thought, it makes sense to just show field handles everywhere, for users with the “Show field handles in edit forms” preference enabled, so reverted that last change you made.

Also changed it up a bit so there’s now generic support for condition rules to supply “hints” (similar to Selectize menus), rather than `BaseCondition` having explicit support for `FieldConditionRuleInterface`.

**Pull request merged**
