### PR TITLE
date range - add inclusive endDate option

### PR DESCRIPTION
**Pull request by i-just**
### Description
Adds the ‘Including “To” Date’ checkbox to the Date Range condition (for backwards compatibility). When checked, the “To” date  (endDate) is included in the query. The checkbox is unchecked by default.

Screenshot 2023-07-17 at 12 48 00

### Related issues
#13435

### CODE REVIEW

**Comment by brandonkelly** [comment]
The added setting seems unnecessary. I think most people would expect that the “To” date would be inclusive, and that the current behavior is wrong.

**Comment by i-just** [comment]
@brandonkelly, sure, a bit, but I added it for backwards compatibility. My thinking was that people might be relying on the current “wrong” behaviour, and without the added setting, e.g. custom sources would start pulling in a broader set of elements. If that’s unnecessary/too cautious, I’m happy to drop it. Or, we could go ahead with this and then drop the setting for 4.6 or 5.0?

**Comment by brandonkelly** [comment]
Yeah let’s just make the change for 4.6 and let it be a sight change in behavior.

**Comment by i-just** [comment]
Extra setting dropped.

**Pull request merged**
