### PR TITLE
Updates DbConfig.php to support pdo_mysql.default_socket path

### PR DESCRIPTION
**Pull request by ldennison-bsd**
Updates DbConfig.php to support pdo_mysql.default_socket path to support Unix socket usage in MySQL DB connections

### CODE REVIEW

**Comment by ldennison-bsd** [comment]
This is related to #3517 .

**Comment by ldennison-bsd** [comment]
It's important to note that this change may be destructive (i.e. cause issues) if the application's webserver is configured with a default socket path that's incorrect. There's a larger potential solution here where the socket path is tested for validity instead of being assumed to be correct.

**Comment by brandonkelly** [comment]
I don’t see how we could make this change (or #3517) without breaking several Craft installs, and testing DB config settings on every request isn’t a great solution. Craft should be able to assume that DB connection settings are correct.

**Comment by brandonkelly** [comment]
You could manually support this on a per-install basis by adding this line to `config/db.php`:

```php
'unixSocket' => ini_get('pdo_mysql.default_socket') ?: null,
```

**Comment by ldennison-bsd** [comment]
Indeed, testing multiple DB connections isn't the greatest, but the test could be simply that the socket file exists. For example, the default MySQL location on many installs is /var/lib/mysql/mysql.sock. If that reference doesn't exist (which should be a trivial file_exists()), then it could be assumed the socket doesn't exist. So the code change here could be updated with a file_exists on that socket path to likely address the concern of broken installs for misconfigured server environments.

**Comment by brandonkelly** [comment]
Just because the file exists doesn’t necessarily mean that it’s pointing to the same DB that the Craft site should be talking to.

**Comment by brandonkelly** [comment]
We talked about this internally and decided Craft shouldn’t be making an assumption that just because `pdo_mysql.default_socket` is set to an existing file path, that it should be using it.

**Pull request closed without merging**
