### PR TITLE
data-type attributes for matrix blocks and fields

### PR DESCRIPTION
**Pull request by swey**
It's nearly impossible for plugins to style matrix blocks and fields. For that reason `data-type` was added to the those blocks and all fields. (The matrix buttons already have a `data-type` attribute but the added blocks have no reference to that type/handle)

For example the change enables stylings like:
```
.matrixblock[data-type="quote"] .field[data-type="position"] {
	background: lightgreen;
	padding: 10px;
}
```

### CODE REVIEW

**Comment by brandonkelly** [comment]
For fields, why not just use the `#field-id`, which is already there and based on the `id` variable?

**Comment by swey** [comment]
Hi @brandonkelly 
For *fields* there is a workaround for few cases. The example above could look like:
```
.field[id^="fields-articleBody-"][id$="-position-field"]
```
But two problems with that solution:
1. Because that `id` is always different, the selector is quite dirty
2. No way to address only `position` inside `quote`. In the demo's `articleBody` it would also address `position` inside `text` and `image`


If `data-type` will be added to the *block types*, the selector would look like:
```
.matrixblock[data-type="quote"] .field[id^="fields-articleBody-"][id$="-position-field"]
```
That would work, but is still quite dirty.
Thank you!

**Comment by brandonkelly** [comment]
Maybe change that to `{% if fieldId %} data-id="{{ fieldId }}"{% endif %}` then.

**Comment by swey** [comment]
But that doesn't help. To stay with the example from above.

Your solution would result in:
bildschirmfoto 2017-07-28 um 06 10 21

My solution results in:
bildschirmfoto 2017-07-28 um 06 10 57


If you don't like it here, I can make a new PR only for the matrix block types? That part is ok for you?

**Comment by brandonkelly** [comment]
Are you sure about that? Just did a test and my code resulted in 

```html
<div class="field" id="fields-articleBody-205-fields-position-field" data-id="position-field">
```

**Comment by brandonkelly** [comment]
(The `id` attribute will get namespaced, but `data-id` won't.)

**Comment by swey** [comment]
Well, I have that version running on my local machine and it's working as expected.

Also check the definition of the used `id`:
https://github.com/craftcms/cms/blob/develop/src/templates/_includes/field.html#L23

**Comment by brandonkelly** [comment]
"working as expected" meaning you got the namespaced result, or what I pasted?

**Comment by swey** [comment]
Because `id` ist set to `handle`, only the `handle` is in my data attribute:
https://github.com/craftcms/cms/blob/develop/src/templates/_includes/field.html#L23

bildschirmfoto 2017-07-28 um 06 10 57

Have you tested it with my branch?

**Comment by brandonkelly** [comment]
I don’t want to call it `data-type` because the ID isn’t a type. Is your only issue that `fieldId` gets suffixed with `-field`? `fieldId` is the correct variable to use here, as `id` refers to the ID of the actual input that is passed into the field template, but here we are putting this on the field container, not the input inside it.

**Comment by swey** [comment]
- I called it `data-type` because the attribute is `data-type` in similar cases. But ok, the similar case is in the context of block types
- An `id` is always unique, like the attribute `id`. It makes no sense to have an `id` and a `data-id` with two different values.
- Probably `data-handle` is the best name. But so far we did not discuss the naming of the attribute, we discussed the reason for that extra attribute
- As said before: The main problem is that there is NO WAY to have a *block type* selector. The thing we are discussing is an additional change. So that's the smaller problem. But again: Even this change makes sense because at the moment you can't have a concrete selector and have to play again with `$=`

**Comment by swey** [comment]
Once again: There is no possible way to have a CSS selector for **block types**. But I will stay with my fork or add the needed attributes with JS.

**Comment by brandonkelly** [comment]
> I called it `data-type` because the attribute is `data-type` in similar cases. But ok, the similar case is in the context of block types

I think I see where you’re coming from now. From my perspective, this is not a similar case though, because this is a generic template that is used for pretty much every field in the Control Panel (not just custom fields), so `id` is rarely going to be a field handle. Maybe a better way to go would be to allow things that are rendering that `_includes/forms/field` template to define custom `data` attributes. Then we can take advantage of that when loading the template to display a custom field, and give it a `data-handle` attribute set to the field’s handle.

> An `id` is always unique, like the attribute `id`. It makes no sense to have an `id` and a `data-id` with two different values.

Technically, the `id` attribute will become unique thanks to namespacing that is applied to the template render output, but the `data-id` attribute would not. So they are different values, and `data-id` would give you the CSS hook you are looking for. But from a semantics perspective I agree with you here – it is awkward at the least.

> As said before: The main problem is that there is NO WAY to have a **block type** selector. The thing we are discussing is an additional change. So that's the smaller problem. But again: Even this change makes sense because at the moment you can't have a concrete selector and have to play again with `$=`

To be clear, I’m fine with `data-type` attribute you proposed for the Matrix block template. Only debating the `data-type` attribute on the general field template.

**Pull request closed without merging**
