### PR TITLE
BaseOptionsField::EVENT_SET_INPUT_OPTIONS

### PR DESCRIPTION
**Pull request by friartuck6000**
Adds an event, and a slight change to surrounding code, to option fields. This allows plugins and modules to modify the options that are rendered for the input.

**Related discussion:** #12212

### CODE REVIEW

**Comment by brandonkelly** [comment]
Seems like this could have been simplified if the event was added to `BaseOptionsField::options()` instead?

**Comment by friartuck6000** [comment]
That was my first thought, but `BaseOptionsField::options()` is used for other things besides generating the input HTML. My goal was to keep this event scoped to only affecting input markup, the way [`EVENT_SET_FIELD_BLOCK_TYPES`](https://github.com/craftcms/cms/blob/main/src/fields/Matrix.php#L692) is for Matrix.

**Comment by brandonkelly** [comment]
Ah ok. In that case it could be added to `translatedOptions()` which is already effectively the same as `inputOptions()`. And we can rename `translatedOptions()` to `inputOptions()` in Craft 5.

**Comment by friartuck6000** [comment]
The difference is that `translatedOptions()` doesn't get passed the `$value` or `$element` args from `inputHtml()`, which are a key part of making the event useful. We would have to change the signature of `translatedOptions()` to accept those. I guess that wouldn't _technically_ be a breaking change since it's not a public method, but it still kinda feels like one, since plugins and user modules could still be using or overriding it.

**Comment by brandonkelly** [comment]
Adding a new `$options` argument to the beginning of `translatedOptions()` would have been a worse breaking change than adding new `$value` and `$element` arguments _after_ `$encode`.

So just dropped `inputOptions()` and the `$option` argument from `translatedOptions()`, and added `$value` and `$element`, and merged for Craft 4.4 🎉

**Comment by friartuck6000** [comment]
Heck of a point 🤦‍♂️ thanks!

**Pull request merged**
