### PR TITLE
Only return true descendants, not the parent.

### PR DESCRIPTION
**Pull request by leevigraham**
Fixes https://github.com/craftcms/cms/issues/12536.

Adding an `_` to the `like` query ensures there's at least one character after the parent folder slash.

MYSQL `_` reference: https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html#operator_like
Postgres `_` reference: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-LIKE

Screenshot 2023-01-15 at 9 49 18 pm

### CODE REVIEW

**Comment by leevigraham** [comment]
I've just reverted this PR to a draft because this change may have unintentional consequences when moving folders:

Screenshot 2023-01-15 at 10 01 00 pm

**Comment by leevigraham** [comment]
A safer way to get descendants could be traversing the tree using parentId and multiple queries or switching to a nested set (like structures). In my case I've got duplicate paths and `getAllDescendantFolders` deletes folders that aren't part of the `parentId` structure.

**Comment by leevigraham** [comment]
Example recursive function:

```sql
WITH RECURSIVE descendants AS
(
SELECT vf.* FROM volumefolders vf WHERE vf.parentId IS NULL
UNION ALL
SELECT vf2.* FROM volumefolders vf2 JOIN descendants 
ON descendants.id = vf2.parentId
)
SELECT * FROM descendants ORDER BY path;
```

image

**Comment by brandonkelly** [comment]
See https://github.com/craftcms/cms/issues/12536#issuecomment-1414425227

**Pull request closed without merging**
