### PR TITLE
correct some translations

### PR DESCRIPTION
**Pull request by xssworm**
added two lines of translation and corrected some inconsistent translations

### CODE REVIEW

**Comment by xssworm** [comment]
Now I think it's an accurate version, I will not make any changes for a period of time.

**Comment by ebeauchamps** [comment]
Will the translation still be located on phraseapp.com ? do we have to check the translations within the beta?

**Comment by takobell** [comment]
Thanks again, @xssworm!

@ebeauchamps with Craft 3, we're migrating away from PhraseApp in favor is Github for managing CP translations.l

**Comment by ebeauchamps** [comment]
Well, you were using Github for translations back to version 1 through 2.1 or 2.2...I understand the price tag for Phraseapp must be heavy, but Github doesn't have all the nice capacities of PhraseApp.


Cheers,



________________________________
De : Brad Bell <notifications@github.com>
Envoyé : mardi 7 mars 2017 19:34
À : craftcms/cms
Cc : Emmanuel Beauchamps; Mention
Objet : Re: [craftcms/cms] correct some translations (#1464)


Thanks again, @xssworm<https://github.com/xssworm>!

@ebeauchamps<https://github.com/ebeauchamps> with Craft 3, we're migrating away from PhraseApp in favor is Github for managing CP translations.l

**Comment by takobell** [comment]
@ebeauchamps before PhraseApp we were on https://www.transifex.com/.  It's not so much the cost of PhraseApp, it's that Github does 95% of what we need for translations and some of them better than PhraseApp.

**Pull request merged**
