### PR TITLE
Anonymise logs

### PR DESCRIPTION
**Pull request by lukeyouell**
Due to GDPR it would be really handy if we were able to anonymise the log prefixes. 

This PR allows for log anonymisation to be enabled from the general config file.

### CODE REVIEW

**Comment by brandonkelly** [comment]
@lukeyouell you mainly just don't want the IP in there right?

**Comment by lukeyouell** [comment]
That's correct, but I thought it would make sense to remove the user & session ID as well. 

I can alter the code to keep these if you'd prefer?

**Comment by brandonkelly** [comment]
Took it in a slightly different direction, because I’d rather avoid creating a new config setting for this. So now `craft\log\FileTarget` has a new `$includeUserIp` property, which is `false` by default.

If you really need to show IP addresses for debugging purposes or whatever, you can enable it from `config/app.php`:

```php
return [
    'components' => [
        'log' => function() {
            $config = craft\helpers\App::logConfig();
            if ($config) {
                $config['targets'][0]['includeUserIp'] = true;
                return Craft::createObject($config);
            }
            return null;
        },
    ],
];
```

**Comment by lukeyouell** [comment]
Sounds good to me! Cheers Brandon.

**Pull request closed without merging**
