### PR TITLE
Adding redis support

### PR DESCRIPTION
**Pull request by fmolina24**
Regarding #1314 
- Added yiisoft/yii2-redis package.
- Added redis as a cache option in common.php
- Added redis default config.
- Added redis as a category to Config service.

### CODE REVIEW

**Comment by takobell** [comment]
Closing this per: https://github.com/craftcms/cms/issues/1314#issuecomment-276812639

**Comment by wesrice** [comment]
Hey @takobell and @brandonkelly,

For a bit of meta discussion, I guess there are a few philosophies that P&T could take on a pull request like this, and others (like [my pull request](https://github.com/craftcms/cms/pull/1317)).

On one hand, I understand the complete hesitance of creating new features in the core of the CMS. That could possibly open pandora's box for P&T and should be guarded. In my opinion, and from what I can tell of yours, new features should strive to exist in plugins, rather than pull requests.

Is adding cache drivers something that can be accomplished via a plugin now? Should there be a first party Redis plugin to bridge v2 installs into the v3 era? This could be useful in transitioning an app from v2 to v3, given that v2 has first party support for Redis.

**Comment by brandonkelly** [comment]
Yes, a plugin could change the caching driver by doing this from `init()`:

```php
Craft::$app->set('cache', [
    'class' => yii\redis\Cache::class,
    'redis' => [
        'hostname' => Craft::$app->config->get('hostname', 'redis'),
        'port' => Craft::$app->config->get('port', 'redis'),
        'database' => Craft::$app->config->get('database', 'redis')
    ]
];
```

The only caveat is, there's some possibility that another plugin will get initialized before this one, and it may need to read from/write to the data cache from its `init()` method. Which would go to whatever the configured cache driver is (i.e. File).

Alternatively, it would be easy enough to implement Redis without a plugin.

    composer require yiisoft/yii2-redis

Then add a `config/app.php` file if there isn't one already, and add this:

```php
<?php

return [
    'components' => [
        'cache' => [
            'class' => yii\redis\Cache::class,
            'redis' => [
                'hostname' => getenv('REDIS_HOSTNAME'),
                'port' => getenv('REDIS_PORT'),
                'database' => getenv('REDIS_DB'),
            ]
        ],
    ],
    // ...
];
```

**Comment by takobell** [comment]
@wesrice Generally speaking, we'll prefer plugins rather than bloating core.

**Pull request closed without merging**
