### PR TITLE
Fixed test suite type compatibility

### PR DESCRIPTION
**Pull request by boboldehampsink**
Fixes

```
Fatal error: Declaration of craft\test\Craft::_afterSuite() must be compatible with Codeception\Module\Yii2::_afterSuite(): void in /app/user/vendor/craftcms/cms/src/test/Craft.php on line 143
```

### CODE REVIEW

**Comment by boboldehampsink** [comment]
This is fixed in Craft 4. Note that in this file of Craft 3 the _beforeSuite already has a void return type as well.

**Comment by brandonkelly** [comment]
Thanks!

**Comment by boboldehampsink** [comment]
@brandonkelly this was not included in 3.8.2?

**Comment by brandonkelly** [comment]
Doh… missed that the PR target was `3.8`. That branch is no longer active. Just merged into `v3` for the next release.

**Pull request merged**
