### PR TITLE
Fix for #12557

### PR DESCRIPTION
**Pull request by angrybrad**
Works around a MySQL bug https://bugs.mysql.com/bug.php?id=109685

### CODE REVIEW

**Comment by mrsimonbennett** [comment]
Hey @angrybrad I am not sure if this is the best fix

This has been affecting our customers, (some of which use SnapShooter to backup craft)

By removing the --single-tranaction flag you're changing the way the backup will run and could cause issues that users would not expect. I know it was not ideal the way MySQL did the bug fix, but it was to fix an issue with the --single-transaction backup

We have been advising users to most ideally [update there grant permissions ](https://snapshooter.com/docs/fixing-mysqldump-couldn-t-execute-flush-tables-access-denied/)


```
GRANT RELOAD,PROCESS ON *.* TO 'backups'@'%';
FLUSH PRIVILEGES;
```

I know its not ideal at all!

**Comment by afairhurst** [comment]
@mrsimonbennett

I ran into this issue today (unable to backup database). Your solution to update grant permissions worked for me. Thank you!

**Comment by mohamedhafez** [comment]
@mrsimonbennett is there any reason we can't just grant the minimum permissions necessary with `GRANT SHOW_TABLES ON *.* TO 'backups'@'%';`? will it just fail with other errors later on, or is there a possibility it will work with just `SHOW_TABLES` for some people?

**Comment by mrsimonbennett** [comment]
> @mrsimonbennett is there any reason we can't just grant the minimum permissions necessary with `GRANT SHOW_TABLES ON *.* TO 'backups'@'%';`? will it just fail with other errors later on, or is there a possibility it will work with just `SHOW_TABLES` for some people?
> 
> 
> 
> 

We need to allow the MySQL user to call some commands that are now required, you can read more about it in the MySQL bug fix. But basically they need to be able to flush the database first now as part of a single transaction backup

**Comment by darylknight** [comment]
For users who land here and are using Ploi, this is what worked for us:

```
mysql -u username -p
GRANT RELOAD,PROCESS ON *.* TO 'ploi'@'%';   < this is for the automated backups
GRANT RELOAD,PROCESS ON *.* TO 'database_user'@'127.0.0.1';   < this is for the database user if you pull down your databases using Craft Scripts
FLUSH PRIVILEGES;
```

**Comment by angrybrad** [comment]
@mrsimonbennett agree it's all gross, but it's a lowest common denominator workaround. The alternative is that we start requiring a _server wide_ privilege for less privileged users to be able to complete a backup in Craft. Even if we wanted to do that, plenty of hosts won't allow it (like AWS RDS), even though it's probably less of an issue if you're hosting on DO and/or using a provisioning service.

Honestly, I'm hoping they revert the change in the next release as it's quite a bad one.

**Comment by darylknight** [comment]
Does removing the single-transaction flag mean that if someone saves an entry during the backup, the backup file will be corrupted? Because it might have already backed up one table that relies on another that has been changed?

**Comment by jeromecoupe** [comment]
Was bitten by this one #13014

**Comment by angrybrad** [comment]
@esbiorn I don’t think detecting the `mysqldump` version vs. the MySQL version addresses the underlying issue, though. The underlying problem is that the `mysqldump` version is out of sync with the database version it’s running against. Or at the very least, using an older version of `mysqldump` to back up a newer version of MySQL can be problematic.

`mysqldump`, in general, seems to be pretty backward compatible. I’ve never seen a problem running a newer version of `mysqldump` against an older database (not even ever had to use the [compatible](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_compatible) flag).

**Pull request merged**
