### PR TITLE
Dotenv stability on multithread envs

### PR DESCRIPTION
**Pull request by TimvanDijkhuizen**
The getenv function is very unstable on a multithread env. This commit replaces all calls to getenv() with Craft::getEnv(), which grabs the variable from $_SERVER instead.

The behavior of Craft::getEnv() is pretty much the same as getenv(). The only difference is that varname is required for this function.

### CODE REVIEW

**Comment by TimvanDijkhuizen** [comment]
This PR fixes https://github.com/craftcms/cms/issues/3631

**Comment by TimvanDijkhuizen** [comment]
Before this change my install would break every few requests because of missing variables. After this change it loads without any problems.

**Comment by TimvanDijkhuizen** [comment]
Update: Even though this commit seems to reduce how often this bug occurs it does not seem to have fixed it.

**Comment by TimvanDijkhuizen** [comment]
> If you try changing how you load dotenv to this in a multithreaded environment [#3631 (comment)](https://github.com/craftcms/cms/issues/3631#issuecomment-457849474) does it work for you?

I've implemented the code suggested by that user which broke the getenv() function. After replacing all getenv() calls in my config and bootstrap files with $_SERVER[] everything seems to be working really well. All of my requests 1800+ test requests survived.

It looks like this PR combined with replacing the dotenv load code fixes this issue. All getenv() calls before the Craft bootstrap is loaded would have to be replaced by $_SYSTEM which is not very clean. So that is something to think about.

**Comment by angrybrad** [comment]
> which broke the getenv() function

Can you elaborate on that?  What sort of error(s) were you getting?

**Comment by TimvanDijkhuizen** [comment]
> > which broke the getenv() function
> 
> Can you elaborate on that? What sort of error(s) were you getting?

There weren't any errors but none of my variables were returning their value. I placed the following piece of code right after the code used to load dotenv:

```php
var_dump(getenv('SECURITY_KEY'));
exit();
```

Which returned the boolean value false. According to the PHP docs that means the variable doesn't exist.

**Comment by angrybrad** [comment]
Got it... looks like by overriding the default adaptors (https://github.com/vlucas/phpdotenv/blob/3.6/src/Environment/DotenvFactory.php#L34), the putenvadaptor isn't loaded, so there's nothing for getenv to load.

**Comment by brandonkelly** [comment]
New Craft projects aren’t even setting environment variables to the `$_SERVER` array anymore, as of last week (see craftcms/craft#55).

**Comment by TimvanDijkhuizen** [comment]
@brandonkelly Would it be safe to use $_ENV instead? That constants doesn't seem to be getting logged.

I'm still trying to work something out as my Craft installations are pretty much unusable on Windows with WAMP. My env variables fail to load 1 out of 5 times and they never load for job and CLI requests. The project I'm working on uses the queue for important API requests and I am unable to work on those now.

Is there anything we can do about this?

**Comment by brandonkelly** [comment]
That change would have affected both `$_ENV` and `$_SERVER`. I ended up reverting craftcms/craft#55 though, so we can revisit this. `$_ENV` does seem like a better place to check than `$_SERVER`.

I’d suggest you make these changes though:

- Rename `getEnv()` to `env()` and move it to `craft\helpers\App`.
- Change it to simply return:
    ```php
    return $_ENV[$name] ?? getenv($name);
    ```
    so `getenv()` is still used as a fallback in case environment variables didn’t make it into `$_ENV`.

**Comment by brandonkelly** [comment]
Actually I’ll go ahead and push up those changes…

**Comment by brandonkelly** [comment]
Craft 3.4.18 is out now with this change.

**Pull request closed without merging**
