### PR TITLE
Date and time formatting labels

### PR DESCRIPTION
**Pull request by gcamacho079**
### Description
Adds visually-hidden formatting helper text to date and time fields.

### Related issues
Resolves DEV-216, DEV-254

### CODE REVIEW

**Comment by brandonkelly** [comment]
@gcamacho079 I’ve added dynamic human-friendly labels to those hidden `span`s, but only for desktop browsers at the moment. So long as mobile gets the native inputs, it seems like the formatting labels aren’t going to really be necessary?

(If we decide to switch to non-native date/time inputs for mobile, we can easily add the formatting labels at that point, but that should be done in a separate PR.)

**Comment by brandonkelly** [comment]
Whoops, didn’t mean to close.

**Comment by gcamacho079** [comment]
@brandonkelly just tested this and setting `aria-labelledby` on these inputs ended up causing some problems, as it's overriding the `aria-label` attribute. We should definitely move the formatting reference ID to the front of `describedBy`

**Comment by brandonkelly** [comment]
@gcamacho079 Alright, made that change.

**Comment by gcamacho079** [comment]
Looks great, @brandonkelly!

**Pull request merged**
